version: "3.9"
   
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - PGHOST=host.docker.internal
      - PGPORT=5432
      - PGUSER=postgres
      - POSTGRES_DB=cancerllm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      default: {}

  web:
    build: .
    command: bash -c "
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8009:8000"
    environment:
      - POSTGRES_NAME=cancerllm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
