# Generated by Django 4.2.2 on 2023-07-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmtransaction',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=50),
        ),
    ]
